/**
 * =========================================================
 * MIDLIFE PROGRAMMER
 * Sort Renderer
 * =========================================================
 *
 * Responsible for displaying the array and animating the
 * operation stream generated by the sorting algorithms.
 *
 * Supported operations:
 *
 * compare
 * swap
 * write
 * clear
 * sorted
 * merged
 * pivot
 * clearPivot
 * minimum
 * clearMinimum
 */

class SortRenderer {

    /**
     * @param {HTMLElement|string} container
     */
    constructor(container) {

        if (typeof container === "string") {

            this.container =
                    document.querySelector(container);
        } else {

            this.container = container;
        }


        if (!this.container) {

            throw new Error(
                    "SortRenderer: sorting container was not found."
                    );
        }


        this.array = [];
        this.runId = 0;

        this.bars = [];

        this.operations = [];

        this.operationIndex = 0;

        this.running = false;

        this.paused = false;

        this.cancelled = false;

        this.speed = 50;

        this.comparisons = 0;

        this.swaps = 0;


        /*
         * Optional callbacks assigned by app.js.
         */
        this.onComparisonChange = null;

        this.onSwapChange = null;

        this.onComplete = null;

        this.onOperation = null;
    }

    /**
     * =====================================================
     * SET ARRAY
     * =====================================================
     */
    setArray(array) {

        this.stop();

        this.array = [...array];

        this.operations = [];

        this.operationIndex = 0;

        this.comparisons = 0;

        this.swaps = 0;

        this.render();

        this.updateStatistics();
    }

    /**
     * =====================================================
     * RENDER
     * =====================================================
     *
     * Rebuild all bars from the current array.
     */
    render() {

        this.container.innerHTML = "";

        this.bars = [];


        if (this.array.length === 0) {
            return;
        }


        const maximumValue =
                Math.max(...this.array);


        for (
                let index = 0;
                index < this.array.length;
                index++
                ) {

            const bar =
                    document.createElement("div");


            bar.className =
                    "sort-bar";


            bar.dataset.index =
                    index;


            bar.dataset.value =
                    this.array[index];


            /*
             * Convert the array value into a percentage of
             * the available visualisation height.
             */
            const percentage =
                    maximumValue === 0
                    ? 0
                    : (
                            this.array[index]
                            /
                        maximumValue
                            ) * 100;


            bar.style.height =
                    `${percentage}%`;


            this.container.appendChild(bar);

            this.bars.push(bar);
        }
    }

    /**
     * =====================================================
     * SET OPERATIONS
     * =====================================================
     */
    setOperations(operations) {

        this.operations =
                [...operations];

        this.operationIndex = 0;

        this.comparisons = 0;

        this.swaps = 0;

        this.clearTemporaryStates();

        this.updateStatistics();
    }

    /**
     * =====================================================
     * SET SPEED
     * =====================================================
     *
     * Expected value:
     *
     * 1   = slow
     * 100 = fast
     */
    setSpeed(speed) {

        const parsed =
                Number(speed);


        if (!Number.isFinite(parsed)) {
            return;
        }


        this.speed =
                Math.max(
                        1,
                        Math.min(
                                100,
                                parsed
                                )
                        );
    }

    /**
     * =====================================================
     * START
     * =====================================================
     */
    async start() {
        if (this.running && !this.paused) return;
        if (this.running && this.paused) { this.paused = false; return; }
        if (this.operationIndex >= this.operations.length) return;
        const runId = ++this.runId;
        this.running = true;
        this.paused = false;
        this.cancelled = false;
        while (this.operationIndex < this.operations.length) {
            if (runId !== this.runId || this.cancelled) return;
            while (this.paused) {
                await this.sleep(30);
                if (runId !== this.runId || this.cancelled) return;
            }
            // A manual step may have completed the animation while paused.
            if (this.operationIndex >= this.operations.length) return;
            const operation = this.operations[this.operationIndex];
            this.executeOperation(operation);
            this.operationIndex++;
            if (typeof this.onOperation === "function") this.onOperation(operation, this.operationIndex);
            await this.sleep(this.getDelay());
        }
        if (runId !== this.runId || this.cancelled) return;
        this.running = false;
        this.paused = false;
        if (typeof this.onComplete === "function") this.onComplete();
    }

    pause() {

        if (!this.running) {
            return;
        }


        this.paused = true;
    }

    /**
     * =====================================================
     * STEP
     * =====================================================
     *
     * Execute exactly one operation.
     */
    step() {

        /*
         * Do not allow stepping while the asynchronous
         * animation loop is actively running.
         */
        if (
                this.running
                &&
                !this.paused
                ) {

            return false;
        }


        if (
                this.operationIndex
                >=
                this.operations.length
                ) {

            return false;
        }


        const operation =
                this.operations[
                        this.operationIndex
                ];


        this.executeOperation(
                operation
                );


        this.operationIndex++;


        if (
                typeof this.onOperation
                ===
                "function"
                ) {

            this.onOperation(
                    operation,
                    this.operationIndex
                    );
        }


        if (
                this.operationIndex
                >=
                this.operations.length
                ) {

            this.running = false;

            this.paused = false;


            if (
                    typeof this.onComplete
                    ===
                    "function"
                    ) {

                this.onComplete();
            }
        }


        return true;
    }

    /**
     * =====================================================
     * STOP
     * =====================================================
     */
    stop() {
        this.runId++;

        this.cancelled = true;

        this.running = false;

        this.paused = false;
    }

    /**
     * =====================================================
     * RESET ANIMATION
     * =====================================================
     *
     * Return to the beginning while keeping the currently
     * loaded array and operation list.
     */
    resetAnimation() {

        this.stop();

        this.operationIndex = 0;

        this.comparisons = 0;

        this.swaps = 0;

        this.render();

        this.updateStatistics();
    }

    /**
     * =====================================================
     * EXECUTE OPERATION
     * =====================================================
     */
    executeOperation(operation) {

        if (
                !operation
                ||
                !operation.type
                ) {

            return;
        }


        switch (operation.type) {

            case "compare":

                this.handleCompare(
                        operation
                        );

                break;


            case "swap":

                this.handleSwap(
                        operation
                        );

                break;


            case "write":

                this.handleWrite(
                        operation
                        );

                break;


            case "clear":

                this.handleClear(
                        operation
                        );

                break;


            case "sorted":

                this.handleSorted(
                        operation
                        );

                break;


            case "merged":

                this.handleMerged(
                        operation
                        );

                break;


            case "pivot":

                this.handlePivot(
                        operation
                        );

                break;


            case "clearPivot":

                this.handleClearPivot(
                        operation
                        );

                break;


            case "minimum":

                this.handleMinimum(
                        operation
                        );

                break;


            case "clearMinimum":

                this.handleClearMinimum(
                        operation
                        );

                break;
        }
    }

    /**
     * =====================================================
     * COMPARE
     * =====================================================
     */
    handleCompare(operation) {

        this.comparisons++;


        this.forEachIndex(
                operation.indices,
                bar => {

                    if (
                            !bar.classList.contains(
                                    "sorted"
                                    )
                            ) {

                        bar.classList.add(
                                "comparing"
                                );
                    }
                }
        );


        this.updateStatistics();
    }

    /**
     * =====================================================
     * SWAP
     * =====================================================
     */
    handleSwap(operation) {

        if (
                !operation.indices
                ||
                operation.indices.length < 2
                ) {

            return;
        }


        const firstIndex =
                operation.indices[0];

        const secondIndex =
                operation.indices[1];


        /*
         * Prefer values supplied by the algorithm.
         */
        if (
                operation.values
                &&
                operation.values.length >= 2
                ) {

            this.array[firstIndex] =
                    operation.values[0];


            this.array[secondIndex] =
                    operation.values[1];

        } else {

            const temporary =
                    this.array[firstIndex];


            this.array[firstIndex] =
                    this.array[secondIndex];


            this.array[secondIndex] =
                    temporary;
        }


        this.swaps++;


        this.updateBar(
                firstIndex
                );


        this.updateBar(
                secondIndex
                );


        this.setClass(
                firstIndex,
                "swapping",
                true
                );


        this.setClass(
                secondIndex,
                "swapping",
                true
                );


        this.updateStatistics();
    }

    /**
     * =====================================================
     * WRITE
     * =====================================================
     *
     * Used primarily by Merge Sort.
     */
    handleWrite(operation) {

        const index =
                operation.index;


        if (
                index === undefined
                ||
                operation.value === undefined
                ) {

            return;
        }


        const previousValue =
                this.array[index];


        this.array[index] =
                operation.value;


        /*
         * Match MergeSort's movement counter.
         */
        if (
                previousValue
                !==
                operation.value
                ) {

            this.swaps++;
        }


        this.updateBar(index);


        this.setClass(
                index,
                "swapping",
                true
                );


        this.updateStatistics();
    }

    /**
     * =====================================================
     * CLEAR
     * =====================================================
     */
    handleClear(operation) {

        this.forEachIndex(
                operation.indices,
                bar => {

                    bar.classList.remove(
                            "comparing"
                            );

                    bar.classList.remove(
                            "swapping"
                            );
                }
        );
    }

    /**
     * =====================================================
     * SORTED
     * =====================================================
     */
    handleSorted(operation) {

        this.forEachIndex(
                operation.indices,
                bar => {

                    this.removeTemporaryClasses(
                            bar
                            );

                    bar.classList.add(
                            "sorted"
                            );
                }
        );
    }

    /**
     * =====================================================
     * MERGED
     * =====================================================
     *
     * Merge Sort uses this to show that a sub-range has
     * completed a merge.
     */
    handleMerged(operation) {

        this.forEachIndex(
                operation.indices,
                bar => {

                    bar.classList.remove(
                            "comparing"
                            );

                    bar.classList.remove(
                            "swapping"
                            );


                    /*
                     * We intentionally do not permanently mark
                     * intermediate merged ranges as sorted,
                     * because their absolute positions may
                     * change during a later merge.
                     */
                    bar.classList.add(
                            "merged"
                            );
                }
        );


        /*
         * Remove the temporary merge highlight shortly
         * afterwards.
         */
        const indices =
                operation.indices
                ? [...operation.indices]
                : [];


        setTimeout(
                () => {

            this.forEachIndex(
                    indices,
                    bar => {

                        bar.classList.remove(
                                "merged"
                                );
                    }
            );

        },
                Math.max(
                        50,
                        this.getDelay() * 2
                        )
                );
    }

    /**
     * =====================================================
     * PIVOT
     * =====================================================
     */
    handlePivot(operation) {

        this.forEachIndex(
                operation.indices,
                bar => {

                    bar.classList.add(
                            "pivot"
                            );
                }
        );
    }

    /**
     * =====================================================
     * CLEAR PIVOT
     * =====================================================
     */
    handleClearPivot(operation) {

        this.forEachIndex(
                operation.indices,
                bar => {

                    bar.classList.remove(
                            "pivot"
                            );
                }
        );
    }

    /**
     * =====================================================
     * MINIMUM
     * =====================================================
     *
     * Used by Selection Sort.
     */
    handleMinimum(operation) {

        this.forEachIndex(
                operation.indices,
                bar => {

                    bar.classList.add(
                            "minimum"
                            );
                }
        );
    }

    /**
     * =====================================================
     * CLEAR MINIMUM
     * =====================================================
     */
    handleClearMinimum(operation) {

        this.forEachIndex(
                operation.indices,
                bar => {

                    bar.classList.remove(
                            "minimum"
                            );
                }
        );
    }

    /**
     * =====================================================
     * UPDATE BAR
     * =====================================================
     */
    updateBar(index) {

        const bar =
                this.bars[index];


        if (!bar) {
            return;
        }


        const maximumValue =
                Math.max(
                        ...this.array,
                        1
                        );


        const percentage =
                (
                        this.array[index]
                        /
                maximumValue
                        ) * 100;


        bar.style.height =
                `${percentage}%`;


        bar.dataset.value =
                this.array[index];
    }

    /**
     * =====================================================
     * FOR EACH INDEX
     * =====================================================
     */
    forEachIndex(indices, callback) {

        if (!Array.isArray(indices)) {
            return;
        }


        for (const index of indices) {

            const bar =
                    this.bars[index];
            if (bar) {

                callback(
                        bar,
                        index
                        );
            }
        }
    }

    /**
     * =====================================================
     * SET CLASS
     * =====================================================
     */
    setClass(
            index,
            className,
            enabled
            ) {

        const bar =
                this.bars[index];


        if (!bar) {
            return;
        }


        if (enabled) {

            bar.classList.add(
                    className
                    );

        } else {

            bar.classList.remove(
                    className
                    );
        }
    }

    /**
     * =====================================================
     * REMOVE TEMPORARY CLASSES
     * =====================================================
     */
    removeTemporaryClasses(bar) {

        bar.classList.remove(
                "comparing"
                );

        bar.classList.remove(
                "swapping"
                );

        bar.classList.remove(
                "pivot"
                );

        bar.classList.remove(
                "minimum"
                );

        bar.classList.remove(
                "merged"
                );
    }

    /**
     * =====================================================
     * CLEAR TEMPORARY STATES
     * =====================================================
     */
    clearTemporaryStates() {

        for (const bar of this.bars) {

            this.removeTemporaryClasses(
                    bar
                    );
            bar.classList.remove(
                    "sorted"
                    );
        }
    }

    /**
     * =====================================================
     * UPDATE STATISTICS
     * =====================================================
     */
    updateStatistics() {

        if (
                typeof this.onComparisonChange
                ===
                "function"
                ) {

            this.onComparisonChange(
                    this.comparisons
                    );
        }


        if (
                typeof this.onSwapChange
                ===
                "function"
                ) {

            this.onSwapChange(
                    this.swaps
                    );
        }
    }

    /**
     * =====================================================
     * GET DELAY
     * =====================================================
     *
     * Convert the 1-100 speed slider into milliseconds.
     *
     * Slow:
     *     ~500ms
     *
     * Fast:
     *     ~5ms
     */
    getDelay() {

        const minimumDelay = 5;

        const maximumDelay = 500;


        const normalised =
                (this.speed - 1) / 99;


        /*
         * Exponential response gives much finer control
         * over the faster end of the slider.
         */
        return Math.round(
                maximumDelay
                *
                Math.pow(
                        minimumDelay / maximumDelay,
                        normalised
                        )
                );
    }

    /**
     * =====================================================
     * SLEEP
     * =====================================================
     */
    sleep(milliseconds) {

        return new Promise(
                resolve => {

                    setTimeout(
                            resolve,
                            milliseconds
                            );
                }
        );
    }

    /**
     * =====================================================
     * GET PROGRESS
     * =====================================================
     */
    getProgress() {

        if (
                this.operations.length === 0
                ) {

            return 0;
        }


        return (
                this.operationIndex
                /
            this.operations.length
                );
    }

    /**
     * =====================================================
     * IS COMPLETE
     * =====================================================
     */
    isComplete() {

        return (
                this.operations.length > 0
                &&
                this.operationIndex
                >=
                this.operations.length
                );
    }
}